name: new

on:
  push:
    branches: master
  pull_request:
    branches: master
  schedule:
    # workwaround for cannot set timezone, cron will start on Asia/Taipei 02:00
    - cron: "0 4 * * 3"
  workflow_dispatch:

env:
  TZ: Asia/Taipei

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        run: |
              wget https://raw.githubusercontent.com/pexcn/daily/gh-pages/pac/whitelist.pac
              sed -i 's/127.0.0.1:1080/127.0.0.1:7890/' whitelist.pac
              mv whitelist.pac test.pac
              
      - name: Deploy
        #if: github.event_name == 'schedule'
        run: |
          # update gh-pages
          rm -rf New/
          git clone https://github.com/Kirby97/New
          cp -rf test.pac New/Test/.
          # push to gh-pages
          cd New/
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "$(date '+%Y-%m-%d %H:%M:%S')"
          git push https://${{ github.repository_owner }}:${{ secrets.RELEASE_TOKEN }}@github.com/${{ github.repository }}.git
